<?php
// HealthSure Setup Script
// This script helps initialize the database and create the admin account

$host = 'localhost';
$database = 'healthsure_db';

$errors = [];
$success = [];
$diagnostics = [];

// Try different common MySQL configurations
$mysql_configs = [
    ['username' => 'root', 'password' => ''],           // Default XAMPP
    ['username' => 'root', 'password' => 'root'],       // Some XAMPP installations
    ['username' => 'root', 'password' => 'password'],   // Common password
    ['username' => 'root', 'password' => 'mysql'],      // Another common password
];

$pdo = null;
$working_config = null;

// Test MySQL connection with different configurations
foreach ($mysql_configs as $config) {
    try {
        $test_pdo = new PDO("mysql:host=$host", $config['username'], $config['password']);
        $test_pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
        
        // Test if we can actually query
        $test_pdo->query("SELECT 1");
        
        $pdo = $test_pdo;
        $working_config = $config;
        $diagnostics[] = "✓ MySQL connection successful with username: '{$config['username']}'";
        break;
        
    } catch (PDOException $e) {
        $diagnostics[] = "✗ Failed with username: '{$config['username']}' - " . $e->getMessage();
        continue;
    }
}

if ($pdo) {
    try {
    
        // Create database if it doesn't exist
        $pdo->exec("CREATE DATABASE IF NOT EXISTS $database");
        $success[] = "Database '$database' created successfully";
        
        // Connect to the specific database
        $pdo = new PDO("mysql:host=$host;dbname=$database", $working_config['username'], $working_config['password']);
        $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
    
    // Read and execute SQL file
    $sql_file = __DIR__ . '/config/init_db.sql';
    if (file_exists($sql_file)) {
        $sql = file_get_contents($sql_file);
        
        // Split SQL into individual statements
        $statements = array_filter(array_map('trim', explode(';', $sql)));
        
        foreach ($statements as $statement) {
            if (!empty($statement) && !preg_match('/^(CREATE DATABASE|USE)/i', $statement)) {
                $pdo->exec($statement);
            }
        }
        
        $success[] = "Database tables created successfully";
        $success[] = "Sample data inserted successfully";
        $success[] = "Default admin account created (admin@healthsure.com / password)";
        
        // Save working database configuration
        $config_content = "<?php\n";
        $config_content .= "// Database Configuration - Auto-generated by setup\n";
        $config_content .= "define('DB_HOST', '$host');\n";
        $config_content .= "define('DB_NAME', '$database');\n";
        $config_content .= "define('DB_USER', '{$working_config['username']}');\n";
        $config_content .= "define('DB_PASS', '{$working_config['password']}');\n";
        $config_content .= "?>";
        
        file_put_contents(__DIR__ . '/config/database.php', $config_content);
        $success[] = "Database configuration saved successfully";
        
    } else {
        $errors[] = "SQL initialization file not found";
    }
    
    } catch (PDOException $e) {
        $errors[] = "Database error: " . $e->getMessage();
    } catch (Exception $e) {
        $errors[] = "Setup error: " . $e->getMessage();
    }
} else {
    $errors[] = "Could not connect to MySQL with any common configuration";
    $errors[] = "Please check that MySQL is running in XAMPP Control Panel";
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>HealthSure Setup</title>
    <link rel="stylesheet" href="assets/css/style.css">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap" rel="stylesheet">
</head>
<body>
    <div class="auth-container">
        <div class="auth-card" style="max-width: 600px;">
            <div class="auth-header">
                <h2>HealthSure Setup</h2>
                <p>Database Initialization</p>
            </div>
            <div class="auth-body">
                <?php if (!empty($diagnostics)): ?>
                    <div class="alert alert-info" style="background: #e3f2fd; border-color: #2196f3; color: #1976d2;">
                        <h4>Connection Diagnostics:</h4>
                        <ul style="margin: 0; padding-left: 1.5rem; font-family: monospace; font-size: 0.9rem;">
                            <?php foreach ($diagnostics as $diagnostic): ?>
                                <li><?php echo htmlspecialchars($diagnostic); ?></li>
                            <?php endforeach; ?>
                        </ul>
                    </div>
                <?php endif; ?>

                <?php if (!empty($errors)): ?>
                    <div class="alert alert-danger">
                        <h4>Setup Errors:</h4>
                        <ul style="margin: 0; padding-left: 1.5rem;">
                            <?php foreach ($errors as $error): ?>
                                <li><?php echo htmlspecialchars($error); ?></li>
                            <?php endforeach; ?>
                        </ul>
                    </div>
                <?php endif; ?>
                
                <?php if (!empty($success)): ?>
                    <div class="alert alert-success">
                        <h4>Setup Completed Successfully!</h4>
                        <ul style="margin: 0; padding-left: 1.5rem;">
                            <?php foreach ($success as $message): ?>
                                <li><?php echo htmlspecialchars($message); ?></li>
                            <?php endforeach; ?>
                        </ul>
                    </div>
                    
                    <div class="mt-4">
                        <h5>Next Steps:</h5>
                        <ol style="padding-left: 1.5rem;">
                            <li>Delete this setup.php file for security</li>
                            <li>Access the application at <a href="index.php" style="color: var(--primary-color);">index.php</a></li>
                            <li>Login with admin credentials: admin@healthsure.com / password</li>
                            <li>Create additional agents and test the system</li>
                        </ol>
                    </div>
                    
                    <div class="text-center mt-4">
                        <a href="index.php" class="btn btn-primary">Go to Application</a>
                    </div>
                <?php else: ?>
                    <div class="mt-4">
                        <h5>Setup Instructions:</h5>
                        <ol style="padding-left: 1.5rem;">
                            <li><strong>Start XAMPP Services:</strong>
                                <ul style="margin-top: 0.5rem;">
                                    <li>Open XAMPP Control Panel</li>
                                    <li>Start Apache service</li>
                                    <li>Start MySQL service</li>
                                </ul>
                            </li>
                            <li><strong>Check MySQL Configuration:</strong>
                                <ul style="margin-top: 0.5rem;">
                                    <li>Click "Admin" next to MySQL in XAMPP</li>
                                    <li>This opens phpMyAdmin</li>
                                    <li>If it works, MySQL is running correctly</li>
                                </ul>
                            </li>
                            <li><strong>Common Solutions:</strong>
                                <ul style="margin-top: 0.5rem;">
                                    <li>Restart XAMPP completely</li>
                                    <li>Check if port 3306 is blocked</li>
                                    <li>Try running XAMPP as Administrator</li>
                                </ul>
                            </li>
                        </ol>
                        
                        <div class="text-center mt-3">
                            <a href="setup.php" class="btn btn-primary">Retry Setup</a>
                            <a href="http://localhost/phpmyadmin" class="btn btn-outline ml-2" target="_blank">Open phpMyAdmin</a>
                        </div>
                    </div>
                <?php endif; ?>
                
                <div class="mt-4" style="padding-top: 1rem; border-top: 1px solid var(--border-color);">
                    <h6>System Requirements:</h6>
                    <ul style="font-size: 0.875rem; color: var(--text-light);">
                        <li>PHP 7.4 or higher ✓</li>
                        <li>MySQL 5.7 or higher ✓</li>
                        <li>Apache Web Server ✓</li>
                        <li>PDO MySQL Extension ✓</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</body>
</html>
